### ISSUE TITLE
Opiniotated Lambda Bootstrap

### ISSUE THREAD

**Issue by gunnarlium** [aptoma/amp-cli#1]
Should we add a task `amp lambda init`, which runs

    $ amp lambda create `git rev-parse HEAD`
    $ amp lambda alias LATEST \$LATEST
    $ amp lambda alias STABLE 1

Perhaps even create the package.json config, by inferring values (and maybe making it interactive):

```js
  "amp": {
    "lambda": {
      "name": package.name.split('/').pop(),
      "description": package.description,
      "region": "eu-west-1",
      "role": "arn:aws:iam::123456788:role/lambda_basic_execution",
      "memory": 128,
      "timeout": 10,
      "s3": {
        "bucket": "deployment-releases-euw1",
        "path": package.name.split('/').pop() + "-lambda"
      }
    }
  }
```

Maybe best to split config creation and init.

This would reduce the copy and pasting getting started, and encourage a uniform strategy for aliases and naming things.

**Comment by martinj** [comment]
I think a interactive config creation for lambda would be nice. I would probably want that on `init` command since its common practice on other node cli's such as npm and express.

For your suggestion on `amp lambda init`, how about adding a option to `create` instead?

**Comment by gunnarlium** [comment]
I'd actually be happy with `create` setting up the aliases as well. So that you simply run `amp lambda create`.

**Comment by martinj** [comment]
Sounds like a good approach.

**Comment by martinj** [comment]
See if this works for you https://github.com/aptoma/amp-cli/tree/lambda-create-alias its untested.

**Comment by gunnarlium** [comment]
Needed a few tweaks: https://github.com/aptoma/amp-cli/commit/b469850231cd946eed21e44dc2f0088f08b5c031

But seems to work!

**Comment by gunnarlium** [comment]
I would prefer it if it used `git rev-parse HEAD` by default, but no big deal.

**Comment by martinj** [comment]
Thanks for tweaking it. Publishing a new version in a few minutes.
